/**
 * Wiki generation module.
 *
 * Generates Markdown documentation from the code graph:
 * - One page per community (module group)
 * - Index page with architecture overview
 * - API reference sections from exported symbols
 */

import * as fs from 'fs';
import * as path from 'path';
import type { GraphDb } from '../graph/db.js';
import type { CommunityDetector, Community, ArchitectureOverview } from '../communities/index.js';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface WikiPage {
  title: string;
  slug: string;
  content: string;
  /** Associated community id, or 'index' for the overview page */
  communityId: string;
}

export interface WikiResult {
  pages: WikiPage[];
  indexPage: WikiPage;
  totalPages: number;
}

// ─── WikiGenerator ────────────────────────────────────────────────────────────

export class WikiGenerator {
  constructor(
    private readonly db: GraphDb,
    private readonly detector: CommunityDetector,
  ) {}

  /**
   * Generate wiki pages for all communities and an index page.
   */
  generate(): WikiResult {
    const overview = this.detector.overview();
    const pages: WikiPage[] = [];

    for (const community of overview.communities) {
      if (community.nodeCount < 2) continue; // skip isolated files
      const page = this.generateCommunityPage(community);
      pages.push(page);
    }

    const indexPage = this.generateIndexPage(overview, pages);

    return { pages, indexPage, totalPages: pages.length + 1 };
  }

  /**
   * Write wiki pages to disk under `outputDir`.
   */
  writeToDir(outputDir: string): string[] {
    fs.mkdirSync(outputDir, { recursive: true });
    const result = this.generate();
    const written: string[] = [];

    // Write index
    const indexPath = path.join(outputDir, 'README.md');
    fs.writeFileSync(indexPath, result.indexPage.content, 'utf8');
    written.push(indexPath);

    // Write community pages
    for (const page of result.pages) {
      const filePath = path.join(outputDir, `${page.slug}.md`);
      fs.writeFileSync(filePath, page.content, 'utf8');
      written.push(filePath);
    }

    return written;
  }

  // ─── Private page generators ──────────────────────────────────────────────

  private generateIndexPage(overview: ArchitectureOverview, pages: WikiPage[]): WikiPage {
    const lines: string[] = [
      '# Architecture Overview',
      '',
      `> Auto-generated by CGB on ${new Date().toISOString().split('T')[0]}`,
      '',
      '## Summary',
      '',
      `| Metric | Value |`,
      `|--------|-------|`,
      `| Total files | ${overview.totalFiles} |`,
      `| Total nodes | ${overview.totalNodes} |`,
      `| Communities | ${overview.communities.length} |`,
      `| Circular deps | ${overview.cycles.length} |`,
      `| Orphan files | ${overview.orphans.length} |`,
      `| Health score | ${overview.healthScore}/100 |`,
      '',
    ];

    if (overview.healthNotes.length > 0) {
      lines.push('## Health Notes', '');
      for (const note of overview.healthNotes) {
        lines.push(`- ⚠️ ${note}`);
      }
      lines.push('');
    }

    lines.push('## Communities', '');
    for (const page of pages) {
      lines.push(`- [${page.title}](./${page.slug}.md)`);
    }
    lines.push('');

    if (overview.layers.length > 0) {
      lines.push('## Dependency Layers', '', '```');
      for (const layer of overview.layers.slice(0, 10)) {
        const kinds = Object.entries(layer.kinds)
          .map(([k, v]) => `${k}:${v}`)
          .join(', ');
        lines.push(`[${String(layer.nodeCount).padStart(4)} nodes] ${layer.layer}  (${kinds})`);
      }
      lines.push('```', '');
    }

    if (overview.cycles.length > 0) {
      lines.push('## Circular Dependencies', '');
      for (const cycle of overview.cycles) {
        lines.push(`- ${cycle.join(' → ')}`);
      }
      lines.push('');
    }

    return {
      title: 'Architecture Overview',
      slug: 'README',
      content: lines.join('\n'),
      communityId: 'index',
    };
  }

  private generateCommunityPage(community: Community): WikiPage {
    const slug = community.label
      .replace(/[^a-zA-Z0-9-_]/g, '-')
      .replace(/-+/g, '-')
      .toLowerCase();

    const lines: string[] = [
      `# ${community.label}`,
      '',
      `> Role: **${community.role}** | Files: **${community.nodeCount}**`,
      '',
      '## Files',
      '',
    ];

    for (const fp of community.files.slice(0, 40)) {
      lines.push(`- \`${fp}\``);
    }
    if (community.files.length > 40) {
      lines.push(`- *(and ${community.files.length - 40} more)*`);
    }
    lines.push('');

    if (community.hubs.length > 0) {
      lines.push('## Key Symbols', '', '| Name | File | Fan-in |', '|------|------|--------|');
      for (const hub of community.hubs) {
        lines.push(`| \`${hub.name}\` | \`${hub.filePath}\` | ${hub.fanIn} |`);
      }
      lines.push('');
    }

    // List exported nodes
    const exported = this.getExportedNodes(community.files);
    if (exported.length > 0) {
      lines.push('## Exported Symbols', '');
      for (const node of exported.slice(0, 20)) {
        lines.push(`- **\`${node.name}\`** (\`${node.kind}\`) — \`${node.filePath}\``);
        if (node.description) lines.push(`  ${node.description}`);
      }
      lines.push('');
    }

    return {
      title: community.label,
      slug,
      content: lines.join('\n'),
      communityId: community.id,
    };
  }

  private getExportedNodes(files: string[]) {
    const nodes = files.flatMap((fp) => this.db.getNodesByFile(fp));
    return nodes
      .filter((n) => !n.isExternal && ['function', 'class', 'interface', 'type'].includes(n.kind))
      .slice(0, 30);
  }
}
